name: Build firmware

permissions:
  contents: read
  pull-requests: write
  
on:
  workflow_call:
  workflow_dispatch:
  push:

jobs:
  build-avr:
    runs-on: ubuntu-latest
    steps:
    - name : Checkout repository
      uses: actions/checkout@v4
     
    - name : make 01
      uses: brentfpage/action-avr-make@run_make_in_selected_dir
      with:
        dir: AVR_Code
        target: '01'

    - name: Upload variant 01 hex artifacts
      uses: actions/upload-artifact@v4
      with:
        name: asset-hex-01
        path: AVR_Code/labrafirm*01.hex
        compression-level: 0
        if-no-files-found: error

    - name : make clean
      uses: brentfpage/action-avr-make@run_make_in_selected_dir
      with:
        dir: AVR_Code
        target: clean

    - name : make 02
      uses: brentfpage/action-avr-make@run_make_in_selected_dir
      with:
        dir: AVR_Code
        target: '02'

    - name: Upload variant 02 hex artifacts
      uses: actions/upload-artifact@v4
      with:
        name: asset-hex-02
        path: AVR_Code/labrafirm*02.hex
        compression-level: 0
        if-no-files-found: error
