name: Build firmware

permissions:
  contents: read
  pull-requests: write
  
on:
  workflow_call:
  workflow_dispatch:
  push:

jobs:
  build-avr:
    runs-on: ubuntu-latest
    steps:
#      - name : Checkout repository
    - uses: /.github/workflows/action-avr-make
      with:
        dir: AVR_Code

#      - name: Install GNU AVR tools and run make

        #       in the future, separate the installation of the tools and the running of make
#       - name: compile using make
#         working-directory: AVR_Code/USB_BULK_TEST
#         run: make 0x02

    - name: Upload hex artifacts
      uses: actions/upload-artifact@v4
      with:
        name: asset-hex
        path: labrafirm*hex
        compression-level: 0
        if-no-files-found: error
          

