name: Build firmware

permissions:
  contents: read
  pull-requests: write
  
on:
  workflow_call:
    outputs:
      firstword:
        description: the run-id of the workflow run
        value: ${{ jobs.build-hex.outputs.output1 }}
  workflow_dispatch:
  push:

jobs:
  build-hex:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step_get_run_id.outputs.RUN_ID }}
    steps:
    - name : Checkout repository
      uses: actions/checkout@v4
     
    - name : make 01
      uses: brentfpage/action-avr-make@run_make_in_selected_dir
      with:
        dir: AVR_Code
        target: '01'

    - name : make clean
      uses: brentfpage/action-avr-make@run_make_in_selected_dir
      with:
        dir: AVR_Code
        target: clean_o_d

    - name : make 02
      uses: brentfpage/action-avr-make@run_make_in_selected_dir
      with:
        dir: AVR_Code
        target: '02'

    - name: Upload variant hex artifacts
      uses: actions/upload-artifact@v4
      with:
        name: asset-hex
        path: AVR_Code/labrafirm*.hex
        compression-level: 0
        if-no-files-found: error

    - name: Prepare workflow run ID output
      id: step_get_run_id
      run: echo "RUN_ID=${{ github.run_id }}" >> "$GITHUB_OUTPUT"
