name: Define the firmware version

on:
  workflow_call:
    outputs:
      firmware_ver:
        description: the firmware version number 0x000N
        value: ${{jobs.define_ver.outputs.ver_firmware}}

jobs:
  define_ver:
    outputs:
      ver_firmware: 0x0007
